#+title: Consumer Protection and Transport Service Providers

* Introduction

A recent slew of protests and resentment by partners and consumers alike against tech giants like Ola Cabs and Uber represents a coming of age for the revolutionary phenomenon of cab aggregating platforms that took the country by storm in 2013. The promise of cheap and comfortable transport and high 6 to 7-figure incomes for passengers and drivers alike have now eroded and given way to a certain level of disenchantment with the platform, which has been mainly because of the exploitative and unfair practices that these companies engage in. A recent notice sent to Ola Cabs and Uber by the Central Consumer Protection Authority (statutory body established under Consumer Protection Act 2019) has shed light on these unfair practices which include allegations like "surge pricing", "drivers unwilling to turn on air conditioning" and "drivers not accepting online payment via the app" among others. While the CCPA's move to protect the interests of the passengers who avail of these services is important, we must also be able to look at the other side of the proverbial coin, the exploitative relation between cab aggregating platforms and their "transport service providers"[fn:1] and its connection with the problems faced by the passengers. In this article, the author wishes to delve deeper into the legal aspects of the problems faced by such transport service providers and relate them with the provisions of the Consumer Protection Act 2019 (hereafter CPA) also stating the need and the significance of such action under the Act

* Jurisdiction under Consumer Protection Act

Consumer Protection Act 2019, brings with it a new and modernised version of the 1986 Act which is more effective in a modern setting with the advent of the digital economy. In our case particularly the Act has developed upon the definition of the word "Consumer" gieven by the 1986 Act by adding a definition under 2(7) where /"buys any goods"/ or /"avails of any service"/ also refers to offline or online transactions through electronic means. This has thus also helped add online platforms like Ola, Uber, Zomato and Amazon under the purview of the Act. Though for our case regarding "transport service providers, it must be noted that while 2(7) does not allow use of goods and services by the /Consumer/ for /commercial purpose/, an explaination that was added in 1993 also clarifies /commercial purpose/ by stating,  "commercial purpose" does not include use by a person using goods and services exclusively for the purpose of earning his livelihood, by means of self-employment. This fits perfectly into our context, because Cab Aggregating Platforms essentially provide a service which is used by Cab Drivers all over the country to /earn their livelihood/ thus it is imperitive that the exploitation done by such platforms be addressed under the Act.

One distinction that must be made here is that the justification given here does not apply any and all persons that are using Ola and Uber services for making a living, because in many situations Cab Drivers are hired by Companies which run huge platform taxi operations under it. This makes the driver an employee which means that he himself is not using the services, but is being employed by a Company that does so, that is where the power given under the Act does not apply because it essentially becomes a /commercial purpose/ [fn:1]

* Exploitation and Need for Action

As Aditi Surie mentions in her article published in the Economic and Political Weekly, cab aggregating platforms like Ola and Uber work on a 2-sided buiseness model[fn:2]. One the one hand riders are brought on to the platform through competitive cheap pricing and on the other, drivers are onboarded through propective of high revenue and high demand. One of the leading propositions that brought a lot of drivers to the platform in 2014 was the marketting of such platforms helping drivers earn incomes upto 90,000 Rupees. A lot of people also shifted from low income jobs in the informal sector into to the Cab Business. But the entry cost for joining Ola or Uber was relatively high which is why many had to take bank loans, and EMI's for Cars and Smartphones which were 2 basic requirements of the online taxi business model. Today those that invested heavily on the platform are facing a devastating financial crunch. The height of this was seen in the COVID-19 Pandemic where drivers had to risk their health and safety and try to get rides in order to pay their loan installments, in addition to maintaining the basic needs of the dependents.

This was mainly because there was little to no difference in pricing of rides over the years, while the external costs of maintaining operations has increased manifold since 2014. The changes in the economic realities of the country do not reflect in the prices of cab aggregating platforms. In addition to that surge pricing which was very advantageous to drivers has now been disallowed by the Government in their recent bid to bring Ola, Uber and others under public control. News outlets regularly cover incidents of Ola and Uber Cab drivers going on strikes because of the rising fuel prices and the stagnant fares. For Companies it was more important to retain consumer interest in the application and the platform as a whole rather than allow drivers to earn a honest living out of the rides they took. Another illustration of this fact is that 30 % of the income that the driver has made through his services are either taken by the platform or the government, which leaves drivers with not a lot. Many drivers are also thus  unwilling to use the payment methods set by such platforms and will often refuse online payment in favor of offline cash payment.

* Conclusion

Consumer Protection Act was established according to the principles set by the United Nations Economic and Social Council (UNESCO) in 1986, and it was based on the premise that there is a noticeable difference between consumers and corporations, imbalance in economic terms, educational terms and in bargaining power. A similar sort of condition is seen here where the drivers are unable to make their concerns heard and thus have to helplessly accept the exploitative terms of these corporations. Many drivers were brought on to the platform by a falsely misrepresented and widely advertised value of projected earnings. This is a grave misrepresentation and is thus an unfair trade practice. Under 2(47)(/i/)(/f/) making a false or misleading representation concerning the need for, or the usefulness of, any goods or service is also an unfair trade practice, and is thus an infringement of the rights of consumers, which was also seen in Union of India vs Nestle India where the misrepresentation of its packaged noodle product Maggie as "Tasty bhi aur Healthy bhi" which is currently being heard in the Apex Court of the Country[fn:3]. So many moved from the jobs that they previously had in favor of a company that maliciously inflated the projected earnings of those that joined the platform, and took on financial liabilities that they now cannot afford. The Central Consumer Authority as well as Consumer Groups must look at this aspect too when trying to restrict cab aggregating platforms like Ola and Uber from engaging in unfair practices. In addition to that we must develop legal awareness among the affected for the legal routes that can be taken for the problems they face especially under the Consumer Protection Act which is known to be consumer friendly and helps provide quick and efficient justice. 

[fn:1] Lakshmi Engineering Works vs PSG Electricals
[fn:2] [[https://www.epw.in/engage/article/are-ola-and-uber-drivers-entrepreneurs-exploited-workers][Are Ola and Uber Drivers Entreprenuers or Exploited Workers]]
[fn:3] [[https://www.outlookindia.com/website/story/india-news-sc-revives-case-against-nestles-maggi-seeks-damages-of-rs-640-crore/322866][SC Revives Case against Nestle Maggie]]
